
configfile: "config/config.yaml"
include: "rules/predict_synergistic_pairs.smk"
include: "rules/analyze_predicted_pairs.smk"

active_cell_types = [cell_type for cell_type, status in config["cell_types_to_run"].items() if status == "ON"]
rule all:
  input:
    expand("results/synergy_predictions_{cell_type}.tsv", cell_type = active_cell_types)
