
scratch_storage: "/scratch/users/jgalante/Synergy_Analysis/"

cell_types_to_run:
  k562: "ON" # else OFF

download_hic: 
  k562: "https://www.encodeproject.org/files/ENCFF621AIY/@@download/ENCFF621AIY.hic"

encode_predictions:
  k562: "https://www.encodeproject.org/files/ENCFF269DKY/@@download/ENCFF269DKY.bed.gz"

thresholds:
  distance: 2e6
  p300: 5
  